[package]
name = "microshell"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.1"
colored = "2.0.0"
home = "0.5.3"
whoami = "1.2.1"
